// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code. Version 3.4.0.32989
//    <NameSpace>DesarrollosPyC.Com.Facturacion.Comprobantes.Complementos</NameSpace><Collection>List</Collection><codeType>CSharp</codeType><EnableDataBinding>False</EnableDataBinding><EnableLazyLoading>False</EnableLazyLoading><TrackingChangesEnable>False</TrackingChangesEnable><GenTrackingClasses>False</GenTrackingClasses><HidePrivateFieldInIDE>False</HidePrivateFieldInIDE><EnableSummaryComment>True</EnableSummaryComment><VirtualProp>False</VirtualProp><IncludeSerializeMethod>True</IncludeSerializeMethod><UseBaseClass>False</UseBaseClass><GenBaseClass>False</GenBaseClass><GenerateCloneMethod>False</GenerateCloneMethod><GenerateDataContracts>False</GenerateDataContracts><CodeBaseTag>Net35</CodeBaseTag><SerializeMethodName>Serialize</SerializeMethodName><DeserializeMethodName>Deserialize</DeserializeMethodName><SaveToFileMethodName>SaveToFile</SaveToFileMethodName><LoadFromFileMethodName>LoadFromFile</LoadFromFileMethodName><GenerateXMLAttributes>True</GenerateXMLAttributes><OrderXMLAttrib>False</OrderXMLAttrib><EnableEncoding>False</EnableEncoding><AutomaticProperties>False</AutomaticProperties><GenerateShouldSerialize>False</GenerateShouldSerialize><DisableDebug>False</DisableDebug><PropNameSpecified>Default</PropNameSpecified><Encoder>UTF8</Encoder><CustomUsings></CustomUsings><ExcludeIncludedTypes>False</ExcludeIncludedTypes><EnableInitializeFields>False</EnableInitializeFields>
//  </auto-generated>
// ------------------------------------------------------------------------------
namespace DesarrollosPyC.Com.Facturacion.Comprobantes.Complementos.Nomina.V12
{
    using System;
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System.Collections;
    using System.Xml.Schema;
    using System.ComponentModel;
    using System.IO;
    using System.Text;
    using System.Collections.Generic;


    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.sat.gob.mx/sitio_internet/cfd/catalogos/Nomina")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.sat.gob.mx/sitio_internet/cfd/catalogos/Nomina", IsNullable = false)]
    public enum c_Banco
    {

        /// <comentarios/>
        [Description("BANAMEX")]
        [System.Xml.Serialization.XmlEnumAttribute("002")]
        Item002,

        /// <comentarios/>
        [Description("BANCOMEXT")]
        [System.Xml.Serialization.XmlEnumAttribute("006")]
        Item006,

        /// <comentarios/>
        [Description("BANOBRAS")]
        [System.Xml.Serialization.XmlEnumAttribute("009")]
        Item009,

        /// <comentarios/>
        [Description("BBVA BANCOMER")]
        [System.Xml.Serialization.XmlEnumAttribute("012")]
        Item012,

        /// <comentarios/>
        [Description("SANTANDER")]
        [System.Xml.Serialization.XmlEnumAttribute("014")]
        Item014,

        /// <comentarios/>
        [Description("BANJERCITO")]
        [System.Xml.Serialization.XmlEnumAttribute("019")]
        Item019,

        /// <comentarios/>
        [Description("HSBC")]
        [System.Xml.Serialization.XmlEnumAttribute("021")]
        Item021,

        /// <comentarios/>
        [Description("BAJIO")]
        [System.Xml.Serialization.XmlEnumAttribute("030")]
        Item030,

        /// <comentarios/>
        [Description("IXE")]
        [System.Xml.Serialization.XmlEnumAttribute("032")]
        Item032,

        /// <comentarios/>
        [Description("INBURSA")]
        [System.Xml.Serialization.XmlEnumAttribute("036")]
        Item036,

        /// <comentarios/>
        [Description("INTERACCIONES")]
        [System.Xml.Serialization.XmlEnumAttribute("037")]
        Item037,

        /// <comentarios/>
        [Description("MIFEL")]
        [System.Xml.Serialization.XmlEnumAttribute("042")]
        Item042,

        /// <comentarios/>
        [Description("SCOTIABANK")]
        [System.Xml.Serialization.XmlEnumAttribute("044")]
        Item044,

        /// <comentarios/>
        [Description("BANREGIO")]
        [System.Xml.Serialization.XmlEnumAttribute("058")]
        Item058,

        /// <comentarios/>
        [Description("INVEX")]
        [System.Xml.Serialization.XmlEnumAttribute("059")]
        Item059,

        /// <comentarios/>
        [Description("BANSI")]
        [System.Xml.Serialization.XmlEnumAttribute("060")]
        Item060,

        /// <comentarios/>
        [Description("AFIRME")]
        [System.Xml.Serialization.XmlEnumAttribute("062")]
        Item062,

        /// <comentarios/>
        [Description("BANORTE")]
        [System.Xml.Serialization.XmlEnumAttribute("072")]
        Item072,

        /// <comentarios/>
        [Description("THE ROYAL BANK")]
        [System.Xml.Serialization.XmlEnumAttribute("102")]
        Item102,

        /// <comentarios/>
        [Description("AMERICAN EXPRESS")]
        [System.Xml.Serialization.XmlEnumAttribute("103")]
        Item103,

        /// <comentarios/>
        [Description("BAMSA")]
        [System.Xml.Serialization.XmlEnumAttribute("106")]
        Item106,

        /// <comentarios/>
        [Description("TOKYO")]
        [System.Xml.Serialization.XmlEnumAttribute("108")]
        Item108,

        /// <comentarios/>
        [Description("JP MORGAN")]
        [System.Xml.Serialization.XmlEnumAttribute("110")]
        Item110,

        /// <comentarios/>
        [Description("BMONEX")]
        [System.Xml.Serialization.XmlEnumAttribute("112")]
        Item112,

        /// <comentarios/>
        [Description("VE POR MAS")]
        [System.Xml.Serialization.XmlEnumAttribute("113")]
        Item113,

        /// <comentarios/>
        [Description("ING")]
        [System.Xml.Serialization.XmlEnumAttribute("116")]
        Item116,

        /// <comentarios/>
        [Description("DEUTSCHE")]
        [System.Xml.Serialization.XmlEnumAttribute("124")]
        Item124,

        /// <comentarios/>
        [Description("CREDIT SUISSE")]
        [System.Xml.Serialization.XmlEnumAttribute("126")]
        Item126,

        /// <comentarios/>
        [Description("AZTECA")]
        [System.Xml.Serialization.XmlEnumAttribute("127")]
        Item127,

        /// <comentarios/>
        [Description("AUTOFIN")]
        [System.Xml.Serialization.XmlEnumAttribute("128")]
        Item128,

        /// <comentarios/>
        [Description("BARCLAYS")]
        [System.Xml.Serialization.XmlEnumAttribute("129")]
        Item129,

        /// <comentarios/>
        [Description("COMPARTAMOS")]
        [System.Xml.Serialization.XmlEnumAttribute("130")]
        Item130,

        /// <comentarios/>
        [Description("BANCO FAMSA")]
        [System.Xml.Serialization.XmlEnumAttribute("131")]
        Item131,

        /// <comentarios/>
        [Description("BMULTIVA")]
        [System.Xml.Serialization.XmlEnumAttribute("132")]
        Item132,

        /// <comentarios/>
        [Description("ACTINVER")]
        [System.Xml.Serialization.XmlEnumAttribute("133")]
        Item133,

        /// <comentarios/>
        [Description("WAL-MART")]
        [System.Xml.Serialization.XmlEnumAttribute("134")]
        Item134,

        /// <comentarios/>
        [Description("NAFIN")]
        [System.Xml.Serialization.XmlEnumAttribute("135")]
        Item135,

        /// <comentarios/>
        [Description("INTERBANCO")]
        [System.Xml.Serialization.XmlEnumAttribute("136")]
        Item136,

        /// <comentarios/>
        [Description("BANCOPPEL")]
        [System.Xml.Serialization.XmlEnumAttribute("137")]
        Item137,

        /// <comentarios/>
        [Description("ABC CAPITAL")]
        [System.Xml.Serialization.XmlEnumAttribute("138")]
        Item138,

        /// <comentarios/>
        [Description("UBS BANK")]
        [System.Xml.Serialization.XmlEnumAttribute("139")]
        Item139,

        /// <comentarios/>
        [Description("CONSUBANCO")]
        [System.Xml.Serialization.XmlEnumAttribute("140")]
        Item140,

        /// <comentarios/>
        [Description("VOLKSWAGEN")]
        [System.Xml.Serialization.XmlEnumAttribute("141")]
        Item141,

        /// <comentarios/>
        [Description("CIBANCO")]
        [System.Xml.Serialization.XmlEnumAttribute("143")]
        Item143,

        /// <comentarios/>
        [Description("BBASE")]
        [System.Xml.Serialization.XmlEnumAttribute("145")]
        Item145,

        /// <comentarios/>
        [Description("BANSEFI")]
        [System.Xml.Serialization.XmlEnumAttribute("166")]
        Item166,

        /// <comentarios/>
        [Description("HIPOTECARIA FEDERAL")]
        [System.Xml.Serialization.XmlEnumAttribute("168")]
        Item168,

        /// <comentarios/>
        [Description("MONEXCB")]
        [System.Xml.Serialization.XmlEnumAttribute("600")]
        Item600,

        /// <comentarios/>
        [Description("GBM")]
        [System.Xml.Serialization.XmlEnumAttribute("601")]
        Item601,

        /// <comentarios/>
        [Description("MASARI")]
        [System.Xml.Serialization.XmlEnumAttribute("602")]
        Item602,

        /// <comentarios/>
        [Description("VALUE")]
        [System.Xml.Serialization.XmlEnumAttribute("605")]
        Item605,

        /// <comentarios/>
        [Description("ESTRUCTURADORES")]
        [System.Xml.Serialization.XmlEnumAttribute("606")]
        Item606,

        /// <comentarios/>
        [Description("TIBER")]
        [System.Xml.Serialization.XmlEnumAttribute("607")]
        Item607,

        /// <comentarios/>
        [Description("VECTOR")]
        [System.Xml.Serialization.XmlEnumAttribute("608")]
        Item608,

        /// <comentarios/>
        [Description("B&B")]
        [System.Xml.Serialization.XmlEnumAttribute("610")]
        Item610,

        /// <comentarios/>
        [Description("ACCIVAL")]
        [System.Xml.Serialization.XmlEnumAttribute("614")]
        Item614,

        /// <comentarios/>
        [Description("MERRILL LYNCH")]
        [System.Xml.Serialization.XmlEnumAttribute("615")]
        Item615,

        /// <comentarios/>
        [Description("FINAMEX")]
        [System.Xml.Serialization.XmlEnumAttribute("616")]
        Item616,

        /// <comentarios/>
        [Description("VALMEX")]
        [System.Xml.Serialization.XmlEnumAttribute("617")]
        Item617,

        /// <comentarios/>
        [Description("UNICA")]
        [System.Xml.Serialization.XmlEnumAttribute("618")]
        Item618,

        /// <comentarios/>
        [Description("MAPFRE")]
        [System.Xml.Serialization.XmlEnumAttribute("619")]
        Item619,

        /// <comentarios/>
        [Description("PROFUTURO")]
        [System.Xml.Serialization.XmlEnumAttribute("620")]
        Item620,

        /// <comentarios/>
        [Description("CB ACTINVER")]
        [System.Xml.Serialization.XmlEnumAttribute("621")]
        Item621,

        /// <comentarios/>
        [Description("OACTIN")]
        [System.Xml.Serialization.XmlEnumAttribute("622")]
        Item622,

        /// <comentarios/>
        [Description("SKANDIA")]
        [System.Xml.Serialization.XmlEnumAttribute("623")]
        Item623,

        /// <comentarios/>
        [Description("CBDEUTSCHE")]
        [System.Xml.Serialization.XmlEnumAttribute("626")]
        Item626,

        /// <comentarios/>
        [Description("ZURICH")]
        [System.Xml.Serialization.XmlEnumAttribute("627")]
        Item627,

        /// <comentarios/>
        [Description("ZURICHVI")]
        [System.Xml.Serialization.XmlEnumAttribute("628")]
        Item628,

        /// <comentarios/>
        [Description("SU CASITA")]
        [System.Xml.Serialization.XmlEnumAttribute("629")]
        Item629,

        /// <comentarios/>
        [Description("CB INTERCAM")]
        [System.Xml.Serialization.XmlEnumAttribute("630")]
        Item630,

        /// <comentarios/>
        [Description("CI BOLSA")]
        [System.Xml.Serialization.XmlEnumAttribute("631")]
        Item631,

        /// <comentarios/>
        [Description("BULLTICK CB")]
        [System.Xml.Serialization.XmlEnumAttribute("632")]
        Item632,

        /// <comentarios/>
        [Description("STERLING")]
        [System.Xml.Serialization.XmlEnumAttribute("633")]
        Item633,

        /// <comentarios/>
        [Description("FINCOMUN")]
        [System.Xml.Serialization.XmlEnumAttribute("634")]
        Item634,

        /// <comentarios/>
        [Description("HDI SEGUROS")]
        [System.Xml.Serialization.XmlEnumAttribute("636")]
        Item636,

        /// <comentarios/>
        [Description("ORDER")]
        [System.Xml.Serialization.XmlEnumAttribute("637")]
        Item637,

        /// <comentarios/>
        [Description("AKALA")]
        [System.Xml.Serialization.XmlEnumAttribute("638")]
        Item638,

        /// <comentarios/>
        [Description("CB JPMORGAN")]
        [System.Xml.Serialization.XmlEnumAttribute("640")]
        Item640,

        /// <comentarios/>
        [Description("REFORMA")]
        [System.Xml.Serialization.XmlEnumAttribute("642")]
        Item642,

        /// <comentarios/>
        [Description("STP")]
        [System.Xml.Serialization.XmlEnumAttribute("646")]
        Item646,

        /// <comentarios/>
        [Description("TELECOMM")]
        [System.Xml.Serialization.XmlEnumAttribute("647")]
        Item647,

        /// <comentarios/>
        [Description("EVERCORE")]
        [System.Xml.Serialization.XmlEnumAttribute("648")]
        Item648,

        /// <comentarios/>
        [Description("SKANDIA")]
        [System.Xml.Serialization.XmlEnumAttribute("649")]
        Item649,

        /// <comentarios/>
        [Description("SEGMTY")]
        [System.Xml.Serialization.XmlEnumAttribute("651")]
        Item651,

        /// <comentarios/>
        [Description("ASEA")]
        [System.Xml.Serialization.XmlEnumAttribute("652")]
        Item652,

        /// <comentarios/>
        [Description("KUSPIT")]
        [System.Xml.Serialization.XmlEnumAttribute("653")]
        Item653,

        /// <comentarios/>
        [Description("SOFIEXPRESS")]
        [System.Xml.Serialization.XmlEnumAttribute("655")]
        Item655,

        /// <comentarios/>
        [Description("UNAGRA")]
        [System.Xml.Serialization.XmlEnumAttribute("656")]
        Item656,

        /// <comentarios/>
        [Description("OPCIONES EMPRESARIALES DEL NOROESTE")]
        [System.Xml.Serialization.XmlEnumAttribute("659")]
        Item659,

        /// <comentarios/>
        [Description("CLS")]
        [System.Xml.Serialization.XmlEnumAttribute("901")]
        Item901,

        /// <comentarios/>
        [Description("INDEVAL")]
        [System.Xml.Serialization.XmlEnumAttribute("902")]
        Item902,

        /// <comentarios/>
        [Description("LIBERTAD")]
        [System.Xml.Serialization.XmlEnumAttribute("670")]
        Item670,
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.sat.gob.mx/sitio_internet/cfd/catalogos/Nomina")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.sat.gob.mx/sitio_internet/cfd/catalogos/Nomina", IsNullable = false)]
    public enum c_OrigenRecurso
    {

        /// <comentarios/>
        [Description("Ingresos propios")]
        IP,

        /// <comentarios/>
        [Description("Ingreso federales")]
        IF,

        /// <comentarios/>
        [Description("Ingresos mixtos")]
        IM,
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.sat.gob.mx/sitio_internet/cfd/catalogos/Nomina")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.sat.gob.mx/sitio_internet/cfd/catalogos/Nomina", IsNullable = false)]
    public enum c_PeriodicidadPago
    {

        /// <comentarios/>
        [Description("Diario")]
        [System.Xml.Serialization.XmlEnumAttribute("01")]
        Item01,

        /// <comentarios/>
        [Description("Semanal")]
        [System.Xml.Serialization.XmlEnumAttribute("02")]
        Item02,

        /// <comentarios/>
        [Description("Catorcenal")]
        [System.Xml.Serialization.XmlEnumAttribute("03")]
        Item03,

        /// <comentarios/>
        [Description("Quincenal")]
        [System.Xml.Serialization.XmlEnumAttribute("04")]
        Item04,

        /// <comentarios/>
        [Description("Mensual")]
        [System.Xml.Serialization.XmlEnumAttribute("05")]
        Item05,

        /// <comentarios/>
        [Description("Bimestral")]
        [System.Xml.Serialization.XmlEnumAttribute("06")]
        Item06,

        /// <comentarios/>
        [Description("Unidad obra")]
        [System.Xml.Serialization.XmlEnumAttribute("07")]
        Item07,

        /// <comentarios/>
        [Description("Comisión")]
        [System.Xml.Serialization.XmlEnumAttribute("08")]
        Item08,

        /// <comentarios/>
        [Description("Precio alzado")]
        [System.Xml.Serialization.XmlEnumAttribute("09")]
        Item09,

        /// <comentarios/>
        [Description("Otra Periodicidad")]
        [System.Xml.Serialization.XmlEnumAttribute("99")]
        Item99,
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.sat.gob.mx/sitio_internet/cfd/catalogos/Nomina")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.sat.gob.mx/sitio_internet/cfd/catalogos/Nomina", IsNullable = false)]
    public enum c_TipoContrato
    {

        /// <comentarios/>
        [Description("Contrato de trabajo por tiempo indeterminado")]
        [System.Xml.Serialization.XmlEnumAttribute("01")]
        Item01,

        /// <comentarios/>
        [Description("Contrato de trabajo para obra determinada")]
        [System.Xml.Serialization.XmlEnumAttribute("02")]
        Item02,

        /// <comentarios/>
        [Description("Contrato de trabajo por tiempo determinado")]
        [System.Xml.Serialization.XmlEnumAttribute("03")]
        Item03,

        /// <comentarios/>
        [Description("Contrato de trabajo por temporada")]
        [System.Xml.Serialization.XmlEnumAttribute("04")]
        Item04,

        /// <comentarios/>
        [Description("Contrato de trabajo sujeto a prueba")]
        [System.Xml.Serialization.XmlEnumAttribute("05")]
        Item05,

        /// <comentarios/>
        [Description("Contrato de trabajo con capacitación inicial")]
        [System.Xml.Serialization.XmlEnumAttribute("06")]
        Item06,

        /// <comentarios/>
        [Description("Modalidad de contratación por pago de hora laborada")]
        [System.Xml.Serialization.XmlEnumAttribute("07")]
        Item07,

        /// <comentarios/>
        [Description("Modalidad de trabajo por comisión laboral")]
        [System.Xml.Serialization.XmlEnumAttribute("08")]
        Item08,

        /// <comentarios/>
        [Description("Modalidades de contratación donde no existe relación de trabajo")]
        [System.Xml.Serialization.XmlEnumAttribute("09")]
        Item09,

        /// <comentarios/>
        [Description("Jubilación, pensión, retiro")]
        [System.Xml.Serialization.XmlEnumAttribute("10")]
        Item10,

        /// <comentarios/>
        [Description("Otro contrato")]
        [System.Xml.Serialization.XmlEnumAttribute("99")]
        Item99,
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.sat.gob.mx/sitio_internet/cfd/catalogos/Nomina")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.sat.gob.mx/sitio_internet/cfd/catalogos/Nomina", IsNullable = false)]
    public enum c_TipoDeduccion
    {

        /// <comentarios/>
        [Description("Seguridad social")]
        [System.Xml.Serialization.XmlEnumAttribute("001")]
        Item001,

        /// <comentarios/>
        [Description("ISR")]
        [System.Xml.Serialization.XmlEnumAttribute("002")]
        Item002,

        /// <comentarios/>
        [Description("Aportaciones a retiro, cesantía en edad avanzada y vejez")]
        [System.Xml.Serialization.XmlEnumAttribute("003")]
        Item003,

        /// <comentarios/>
        [Description("Otros")]
        [System.Xml.Serialization.XmlEnumAttribute("004")]
        Item004,

        /// <comentarios/>
        [Description("Aportaciones a Fondo de vivienda")]
        [System.Xml.Serialization.XmlEnumAttribute("005")]
        Item005,

        /// <comentarios/>
        [Description("Descuento por incapacidad")]
        [System.Xml.Serialization.XmlEnumAttribute("006")]
        Item006,

        /// <comentarios/>
        [Description("Pensión alimenticia")]
        [System.Xml.Serialization.XmlEnumAttribute("007")]
        Item007,

        /// <comentarios/>
        [Description("Renta")]
        [System.Xml.Serialization.XmlEnumAttribute("008")]
        Item008,

        /// <comentarios/>
        [Description("Préstamos provenientes del Fondo Nacional de la Vivienda para los Trabajadores")]
        [System.Xml.Serialization.XmlEnumAttribute("009")]
        Item009,

        /// <comentarios/>
        [Description("Pago por crédito de vivienda")]
        [System.Xml.Serialization.XmlEnumAttribute("010")]
        Item010,

        /// <comentarios/>
        [Description("Pago de abonos INFONACOT")]
        [System.Xml.Serialization.XmlEnumAttribute("011")]
        Item011,

        /// <comentarios/>
        [Description("Anticipo de salarios")]
        [System.Xml.Serialization.XmlEnumAttribute("012")]
        Item012,

        /// <comentarios/>
        [Description("Pagos hechos con exceso al trabajador")]
        [System.Xml.Serialization.XmlEnumAttribute("013")]
        Item013,

        /// <comentarios/>
        [Description("Errores")]
        [System.Xml.Serialization.XmlEnumAttribute("014")]
        Item014,

        /// <comentarios/>
        [Description("Pérdidas")]
        [System.Xml.Serialization.XmlEnumAttribute("015")]
        Item015,

        /// <comentarios/>
        [Description("Averías")]
        [System.Xml.Serialization.XmlEnumAttribute("016")]
        Item016,

        /// <comentarios/>
        [Description("Adquisición de artículos producidos por la empresa o establecimiento")]
        [System.Xml.Serialization.XmlEnumAttribute("017")]
        Item017,

        /// <comentarios/>
        [Description("Cuotas para la constitución y fomento de sociedades cooperativas y de cajas de ahorro")]
        [System.Xml.Serialization.XmlEnumAttribute("018")]
        Item018,

        /// <comentarios/>
        [Description("Cuotas sindicales")]
        [System.Xml.Serialization.XmlEnumAttribute("019")]
        Item019,

        /// <comentarios/>
        [Description("Ausencia (Ausentismo)")]
        [System.Xml.Serialization.XmlEnumAttribute("020")]
        Item020,

        /// <comentarios/>
        [Description("Cuotas obrero patronales")]
        [System.Xml.Serialization.XmlEnumAttribute("021")]
        Item021,

        /// <comentarios/>
        [Description("Impuestos Locales")]
        [System.Xml.Serialization.XmlEnumAttribute("022")]
        Item022,

        /// <comentarios/>
        [Description("Aportaciones voluntarias")]
        [System.Xml.Serialization.XmlEnumAttribute("023")]
        Item023,

        /// <comentarios/>
        [Description("Ajuste en Gratificación Anual (Aguinaldo) Exento")]
        [System.Xml.Serialization.XmlEnumAttribute("024")]
        Item024,

        /// <comentarios/>
        [Description("Ajuste en Gratificación Anual (Aguinaldo) Gravado")]
        [System.Xml.Serialization.XmlEnumAttribute("025")]
        Item025,
        /// <comentarios/>
        [Description("Ajuste en Participación de los Trabajadores en las Utilidades PTU Exento")]
        [System.Xml.Serialization.XmlEnumAttribute("026")]
        Item026,
        /// <comentarios/>
        [Description("Ajuste en Participación de los Trabajadores en las Utilidades PTU Gravado")]
        [System.Xml.Serialization.XmlEnumAttribute("027")]
        Item027,
        /// <comentarios/>
        [Description("Ajuste en Reembolso de Gastos Médicos Dentales y Hospitalarios Exento")]
        [System.Xml.Serialization.XmlEnumAttribute("028")]
        Item028,
        /// <comentarios/>
        [Description("Ajuste en Fondo de ahorro Exento")]
        [System.Xml.Serialization.XmlEnumAttribute("029")]
        Item029,
        /// <comentarios/>
        [Description("Ajuste en Caja de ahorro Exento")]
        [System.Xml.Serialization.XmlEnumAttribute("030")]
        Item030,
        /// <comentarios/>
        [Description("Ajuste en Contribuciones a Cargo del Trabajador Pagadas por el Patrón Exento")]
        [System.Xml.Serialization.XmlEnumAttribute("031")]
        Item031,
        /// <comentarios/>
        [Description("Ajuste en Premios por puntualidad Gravado")]
        [System.Xml.Serialization.XmlEnumAttribute("032")]
        Item032,
        /// <comentarios/>
        [Description("Ajuste en Prima de Seguro de vida Exento")]
        [System.Xml.Serialization.XmlEnumAttribute("033")]
        Item033,
        /// <comentarios/>
        [Description("Ajuste en Seguro de Gastos Médicos Mayores Exento")]
        [System.Xml.Serialization.XmlEnumAttribute("034")]
        Item034,
        /// <comentarios/>
        [Description("Ajuste en Cuotas Sindicales Pagadas por el Patrón Exento")]
        [System.Xml.Serialization.XmlEnumAttribute("035")]
        Item035,
        /// <comentarios/>
        [Description("Ajuste en Subsidios por incapacidad Exento")]
        [System.Xml.Serialization.XmlEnumAttribute("036")]
        Item036,
        /// <comentarios/>
        [Description("Ajuste en Becas para trabajadores y/o hijos Exento")]
        [System.Xml.Serialization.XmlEnumAttribute("037")]
        Item037,
        /// <comentarios/>
        [Description("Ajuste en Horas extra Exento")]
        [System.Xml.Serialization.XmlEnumAttribute("038")]
        Item038,
        /// <comentarios/>
        [Description("Ajuste en Horas extra Gravado")]
        [System.Xml.Serialization.XmlEnumAttribute("039")]
        Item039,
        /// <comentarios/>
        [Description("Ajuste en Prima dominical Exento")]
        [System.Xml.Serialization.XmlEnumAttribute("040")]
        Item040,
        /// <comentarios/>
        [Description("Ajuste en Prima dominical Gravado")]
        [System.Xml.Serialization.XmlEnumAttribute("041")]
        Item041,
        /// <comentarios/>
        [Description("Ajuste en Prima vacacional Exento")]
        [System.Xml.Serialization.XmlEnumAttribute("042")]
        Item042,
        /// <comentarios/>
        [Description("Ajuste en Prima vacacional Gravado")]
        [System.Xml.Serialization.XmlEnumAttribute("043")]
        Item043,
        /// <comentarios/>
        [Description("Ajuste en Prima por antigüedad Exento")]
        [System.Xml.Serialization.XmlEnumAttribute("044")]
        Item044,
        /// <comentarios/>
        [Description("Ajuste en Prima por antigüedad Gravado")]
        [System.Xml.Serialization.XmlEnumAttribute("045")]
        Item045,
        /// <comentarios/>
        [Description("Ajuste en Pagos por separación Exento")]
        [System.Xml.Serialization.XmlEnumAttribute("046")]
        Item046,
        /// <comentarios/>
        [Description("Ajuste en Pagos por separación Gravado")]
        [System.Xml.Serialization.XmlEnumAttribute("047")]
        Item047,
        /// <comentarios/>
        [Description("Ajuste en Seguro de retiro Exento")]
        [System.Xml.Serialization.XmlEnumAttribute("048")]
        Item048,
        /// <comentarios/>
        [Description("Ajuste en Indemnizaciones Exento")]
        [System.Xml.Serialization.XmlEnumAttribute("049")]
        Item049,
        /// <comentarios/>
        [Description("Ajuste en Indemnizaciones Gravado")]
        [System.Xml.Serialization.XmlEnumAttribute("050")]
        Item050,
        /// <comentarios/>
        [Description("Ajuste en Reembolso por funeral Exento")]
        [System.Xml.Serialization.XmlEnumAttribute("051")]
        Item051,
        /// <comentarios/>
        [Description("Ajuste en Cuotas de seguridad social pagadas por el patrón Exento")]
        [System.Xml.Serialization.XmlEnumAttribute("052")]
        Item052,
        /// <comentarios/>
        [Description("Ajuste en Comisiones Gravado")]
        [System.Xml.Serialization.XmlEnumAttribute("053")]
        Item053,
        /// <comentarios/>
        [Description("Ajuste en Vales de despensa Exento")]
        [System.Xml.Serialization.XmlEnumAttribute("054")]
        Item054,
        /// <comentarios/>
        [Description("Ajuste en Vales de restaurante Exento")]
        [System.Xml.Serialization.XmlEnumAttribute("055")]
        Item055,
        /// <comentarios/>
        [Description("Ajuste en Vales de gasolina Exento")]
        [System.Xml.Serialization.XmlEnumAttribute("056")]
        Item056,
        /// <comentarios/>
        [Description("Ajuste en Vales de ropa Exento")]
        [System.Xml.Serialization.XmlEnumAttribute("057")]
        Item057,
        /// <comentarios/>
        [Description("Ajuste en Ayuda para renta Exento")]
        [System.Xml.Serialization.XmlEnumAttribute("058")]
        Item058,
        /// <comentarios/>
        [Description("Ajuste en Ayuda para artículos escolares Exento")]
        [System.Xml.Serialization.XmlEnumAttribute("059")]
        Item059,
        /// <comentarios/>
        [Description("Ajuste en Ayuda para anteojos Exento")]
        [System.Xml.Serialization.XmlEnumAttribute("060")]
        Item060,
        /// <comentarios/>
        [Description("Ajuste en Ayuda para transporte Exento")]
        [System.Xml.Serialization.XmlEnumAttribute("061")]
        Item061,
        /// <comentarios/>
        [Description("Ajuste en Ayuda para gastos de funeral Exento")]
        [System.Xml.Serialization.XmlEnumAttribute("062")]
        Item062,
        /// <comentarios/>
        [Description("Ajuste en Otros ingresos por salarios Exento")]
        [System.Xml.Serialization.XmlEnumAttribute("063")]
        Item063,
        /// <comentarios/>
        [Description("Ajuste en Otros ingresos por salarios Gravado")]
        [System.Xml.Serialization.XmlEnumAttribute("064")]
        Item064,
        /// <comentarios/>
        [Description("Ajuste en Jubilaciones, pensiones o haberes de retiro Exento")]
        [System.Xml.Serialization.XmlEnumAttribute("065")]
        Item065,
        /// <comentarios/>
        [Description("Ajuste en Jubilaciones, pensiones o haberes de retiro Gravado")]
        [System.Xml.Serialization.XmlEnumAttribute("066")]
        Item066,
        /// <comentarios/>
        [Description("Ajuste en Pagos por separación Acumulable")]
        [System.Xml.Serialization.XmlEnumAttribute("067")]
        Item067,
        /// <comentarios/>
        [Description("Ajuste en Pagos por separación No acumulable")]
        [System.Xml.Serialization.XmlEnumAttribute("068")]
        Item068,
        /// <comentarios/>
        [Description("Ajuste en Jubilaciones, pensiones o haberes de retiro Acumulable")]
        [System.Xml.Serialization.XmlEnumAttribute("069")]
        Item069,
        /// <comentarios/>
        [Description("Ajuste en Jubilaciones, pensiones o haberes de retiro No acumulable")]
        [System.Xml.Serialization.XmlEnumAttribute("070")]
        Item070,
        /// <comentarios/>
        [Description("Ajuste en Subsidio para el empleo (efectivamente entregado al trabajador)")]
        [System.Xml.Serialization.XmlEnumAttribute("071")]
        Item071,
        /// <comentarios/>
        [Description("Ajuste en Ingresos en acciones o títulos valor que representan bienes Exento")]
        [System.Xml.Serialization.XmlEnumAttribute("072")]
        Item072,
        /// <comentarios/>
        [Description("Ajuste en Ingresos en acciones o títulos valor que representan bienes Gravado")]
        [System.Xml.Serialization.XmlEnumAttribute("073")]
        Item073,
        /// <comentarios/>
        [Description("Ajuste en Alimentación Exento")]
        [System.Xml.Serialization.XmlEnumAttribute("074")]
        Item074,
        /// <comentarios/>
        [Description("Ajuste en Alimentación Gravado")]
        [System.Xml.Serialization.XmlEnumAttribute("075")]
        Item075,
        /// <comentarios/>
        [Description("Ajuste en Habitación Exento")]
        [System.Xml.Serialization.XmlEnumAttribute("076")]
        Item076,
        /// <comentarios/>
        [Description("Ajuste en Habitación Gravado")]
        [System.Xml.Serialization.XmlEnumAttribute("077")]
        Item077,
        /// <comentarios/>
        [Description("Ajuste en Premios por asistencia")]
        [System.Xml.Serialization.XmlEnumAttribute("078")]
        Item078,
        /// <comentarios/>
        [Description("Ajuste en Pagos distintos a los listados y que no deben considerarse como ingreso por sueldos, salarios o ingresos asimilados.")]
        [System.Xml.Serialization.XmlEnumAttribute("079")]
        Item079,
        /// <comentarios/>
        [Description("Ajuste en Viáticos no comprobados")]
        [System.Xml.Serialization.XmlEnumAttribute("080")]
        Item080,
        /// <comentarios/>
        [Description("Ajuste en Viáticos anticipados")]
        [System.Xml.Serialization.XmlEnumAttribute("081")]
        Item081,
        /// <comentarios/>
        [Description("Ajuste en Fondo de ahorro Gravado")]
        [System.Xml.Serialization.XmlEnumAttribute("082")]
        Item082,
        /// <comentarios/>
        [Description("Ajuste en Caja de ahorro Gravado")]
        [System.Xml.Serialization.XmlEnumAttribute("083")]
        Item083,
        /// <comentarios/>
        [Description("Ajuste en Prima de Seguro de vida Gravado")]
        [System.Xml.Serialization.XmlEnumAttribute("084")]
        Item084,
        /// <comentarios/>
        [Description("Ajuste en Seguro de Gastos Médicos Mayores Gravado")]
        [System.Xml.Serialization.XmlEnumAttribute("085")]
        Item085,
        /// <comentarios/>
        [Description("Ajuste en Subsidios por incapacidad Gravado")]
        [System.Xml.Serialization.XmlEnumAttribute("086")]
        Item086,
        /// <comentarios/>
        [Description("Ajuste en Becas para trabajadores y/o hijos Gravado")]
        [System.Xml.Serialization.XmlEnumAttribute("087")]
        Item087,
        /// <comentarios/>
        [Description("Ajuste en Seguro de retiro Gravado")]
        [System.Xml.Serialization.XmlEnumAttribute("088")]
        Item088,
        /// <comentarios/>
        [Description("Ajuste en Vales de despensa Gravado")]
        [System.Xml.Serialization.XmlEnumAttribute("089")]
        Item089,
        /// <comentarios/>
        [Description("Ajuste en Vales de restaurante Gravado")]
        [System.Xml.Serialization.XmlEnumAttribute("090")]
        Item090,
        /// <comentarios/>
        [Description("Ajuste en Vales de gasolina Gravado")]
        [System.Xml.Serialization.XmlEnumAttribute("091")]
        Item091,
        /// <comentarios/>
        [Description("Ajuste en Vales de ropa Gravado")]
        [System.Xml.Serialization.XmlEnumAttribute("092")]
        Item092,
        /// <comentarios/>
        [Description("Ajuste en Ayuda para renta Gravado")]
        [System.Xml.Serialization.XmlEnumAttribute("093")]
        Item093,
        /// <comentarios/>
        [Description("Ajuste en Ayuda para artículos escolares Gravado")]
        [System.Xml.Serialization.XmlEnumAttribute("094")]
        Item094,
        /// <comentarios/>
        [Description("Ajuste en Ayuda para anteojos Gravado")]
        [System.Xml.Serialization.XmlEnumAttribute("095")]
        Item095,
        /// <comentarios/>
        [Description("Ajuste en Ayuda para transporte Gravado")]
        [System.Xml.Serialization.XmlEnumAttribute("096")]
        Item096,
        /// <comentarios/>
        [Description("Ajuste en Ayuda para gastos de funeral Gravado")]
        [System.Xml.Serialization.XmlEnumAttribute("097")]
        Item097,
        /// <comentarios/>
        [Description("Ajuste a ingresos asimilados a salarios gravados")]
        [System.Xml.Serialization.XmlEnumAttribute("098")]
        Item098,
        /// <comentarios/>
        [Description("Ajuste a ingresos por sueldos y salarios gravados")]
        [System.Xml.Serialization.XmlEnumAttribute("099")]
        Item099,

    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.sat.gob.mx/sitio_internet/cfd/catalogos/Nomina")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.sat.gob.mx/sitio_internet/cfd/catalogos/Nomina", IsNullable = false)]
    public enum c_TipoHoras
    {

        /// <comentarios/>
        [Description("Dobles")]
        [System.Xml.Serialization.XmlEnumAttribute("01")]
        Item01,

        /// <comentarios/>
        [Description("Triples")]
        [System.Xml.Serialization.XmlEnumAttribute("02")]
        Item02,

        /// <comentarios/>
        [Description("Simples")]
        [System.Xml.Serialization.XmlEnumAttribute("03")]
        Item03,
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.sat.gob.mx/sitio_internet/cfd/catalogos/Nomina")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.sat.gob.mx/sitio_internet/cfd/catalogos/Nomina", IsNullable = false)]
    public enum c_TipoIncapacidad
    {

        /// <comentarios/>
        [Description("Riesgo de trabajo")]
        [System.Xml.Serialization.XmlEnumAttribute("01")]
        Item01,

        /// <comentarios/>
        [Description("Enfermedad en general")]
        [System.Xml.Serialization.XmlEnumAttribute("02")]
        Item02,

        /// <comentarios/>
        [Description("Maternidad")]
        [System.Xml.Serialization.XmlEnumAttribute("03")]
        Item03,
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.sat.gob.mx/sitio_internet/cfd/catalogos/Nomina")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.sat.gob.mx/sitio_internet/cfd/catalogos/Nomina", IsNullable = false)]
    public enum c_TipoJornada
    {
        /// <comentarios/>
        [Description("Diurna")]
        [System.Xml.Serialization.XmlEnumAttribute("01")]
        Item01,

        /// <comentarios/>
        [Description("Nocturna")]
        [System.Xml.Serialization.XmlEnumAttribute("02")]
        Item02,

        /// <comentarios/>
        [Description("Mixta")]
        [System.Xml.Serialization.XmlEnumAttribute("03")]
        Item03,

        /// <comentarios/>
        [Description("Por hora")]
        [System.Xml.Serialization.XmlEnumAttribute("04")]
        Item04,

        /// <comentarios/>
        [Description("Reducida")]
        [System.Xml.Serialization.XmlEnumAttribute("05")]
        Item05,

        /// <comentarios/>
        [Description("Continuada")]
        [System.Xml.Serialization.XmlEnumAttribute("06")]
        Item06,

        /// <comentarios/>
        [Description("Partida")]
        [System.Xml.Serialization.XmlEnumAttribute("07")]
        Item07,

        /// <comentarios/>
        [Description("Por turnos")]
        [System.Xml.Serialization.XmlEnumAttribute("08")]
        Item08,

        /// <comentarios/>
        [Description("Otra Jornada")]
        [System.Xml.Serialization.XmlEnumAttribute("99")]
        Item99,
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.sat.gob.mx/sitio_internet/cfd/catalogos/Nomina")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.sat.gob.mx/sitio_internet/cfd/catalogos/Nomina", IsNullable = false)]
    public enum c_TipoNomina
    {

        /// <comentarios/>
        [Description("Nómina ordinaria")]
        O,

        /// <comentarios/>
        [Description("Nómina extraordinaria")]
        E,
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.sat.gob.mx/sitio_internet/cfd/catalogos/Nomina")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.sat.gob.mx/sitio_internet/cfd/catalogos/Nomina", IsNullable = false)]
    public enum c_TipoOtroPago
    {

        /// <comentarios/>
        [Description("Reintegro de ISR pagado en exceso (siempre que no haya sido enterado al SAT)")]
        [System.Xml.Serialization.XmlEnumAttribute("001")]
        Item001,

        /// <comentarios/>
        [Description("Subsidio para el empleo (efectivamente entregado al trabajador)")]
        [System.Xml.Serialization.XmlEnumAttribute("002")]
        Item002,

        /// <comentarios/>
        [Description("Viáticos (entregados al trabajador)")]
        [System.Xml.Serialization.XmlEnumAttribute("003")]
        Item003,

        /// <comentarios/>
        [Description("Aplicación de saldo a favor por compensación anual")]
        [System.Xml.Serialization.XmlEnumAttribute("004")]
        Item004,

        /// <comentarios/>
        [Description("Pagos distintos a los listados y que no deben considerarse como ingreso por sueldos, salarios o ingresos asimilados")]
        [System.Xml.Serialization.XmlEnumAttribute("999")]
        Item999,
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.sat.gob.mx/sitio_internet/cfd/catalogos/Nomina")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.sat.gob.mx/sitio_internet/cfd/catalogos/Nomina", IsNullable = false)]
    public enum c_TipoPercepcion
    {

        /// <comentarios/>
        [Description("Sueldos, Salarios  Rayas y Jornales")]
        [System.Xml.Serialization.XmlEnumAttribute("001")]
        Item001,

        /// <comentarios/>
        [Description("Gratificación Anual (Aguinaldo)")]
        [System.Xml.Serialization.XmlEnumAttribute("002")]
        Item002,

        /// <comentarios/>
        [Description("Participación de los Trabajadores en las Utilidades PTU")]
        [System.Xml.Serialization.XmlEnumAttribute("003")]
        Item003,

        /// <comentarios/>
        [Description("Reembolso de Gastos Médicos Dentales y Hospitalarios")]
        [System.Xml.Serialization.XmlEnumAttribute("004")]
        Item004,

        /// <comentarios/>
        [Description("Fondo de Ahorro")]
        [System.Xml.Serialization.XmlEnumAttribute("005")]
        Item005,

        /// <comentarios/>
        [Description("Caja de ahorro")]
        [System.Xml.Serialization.XmlEnumAttribute("006")]
        Item006,

        /// <comentarios/>
        [Description("Contribuciones a Cargo del Trabajador Pagadas por el Patrón")]
        [System.Xml.Serialization.XmlEnumAttribute("009")]
        Item009,

        /// <comentarios/>
        [Description("Premios por puntualidad")]
        [System.Xml.Serialization.XmlEnumAttribute("010")]
        Item010,

        /// <comentarios/>
        [Description("Prima de Seguro de vida")]
        [System.Xml.Serialization.XmlEnumAttribute("011")]
        Item011,

        /// <comentarios/>
        [Description("Seguro de Gastos Médicos Mayores")]
        [System.Xml.Serialization.XmlEnumAttribute("012")]
        Item012,

        /// <comentarios/>
        [Description("Cuotas Sindicales Pagadas por el Patrón")]
        [System.Xml.Serialization.XmlEnumAttribute("013")]
        Item013,

        /// <comentarios/>
        [Description("Subsidios por incapacidad")]
        [System.Xml.Serialization.XmlEnumAttribute("014")]
        Item014,

        /// <comentarios/>
        [Description("Becas para trabajadores y/o hijos")]
        [System.Xml.Serialization.XmlEnumAttribute("015")]
        Item015,

        /// <comentarios/>
        [Description("Horas extra")]
        [System.Xml.Serialization.XmlEnumAttribute("019")]
        Item019,

        /// <comentarios/>
        [Description("Prima dominical")]
        [System.Xml.Serialization.XmlEnumAttribute("020")]
        Item020,

        /// <comentarios/>
        [Description("Prima vacacional")]
        [System.Xml.Serialization.XmlEnumAttribute("021")]
        Item021,

        /// <comentarios/>
        [Description("Prima por antigüedad")]
        [System.Xml.Serialization.XmlEnumAttribute("022")]
        Item022,

        /// <comentarios/>
        [Description("Pagos por separación")]
        [System.Xml.Serialization.XmlEnumAttribute("023")]
        Item023,

        /// <comentarios/>
        [Description("Seguro de retiro")]
        [System.Xml.Serialization.XmlEnumAttribute("024")]
        Item024,

        /// <comentarios/>
        [Description("Indemnizaciones")]
        [System.Xml.Serialization.XmlEnumAttribute("025")]
        Item025,

        /// <comentarios/>
        [Description("Reembolso por funeral")]
        [System.Xml.Serialization.XmlEnumAttribute("026")]
        Item026,

        /// <comentarios/>
        [Description("Cuotas de seguridad social pagadas por el patrón")]
        [System.Xml.Serialization.XmlEnumAttribute("027")]
        Item027,

        /// <comentarios/>
        [Description("Comisiones")]
        [System.Xml.Serialization.XmlEnumAttribute("028")]
        Item028,

        /// <comentarios/>
        [Description("Vales de despensa")]
        [System.Xml.Serialization.XmlEnumAttribute("029")]
        Item029,

        /// <comentarios/>
        [Description("Vales de restaurante")]
        [System.Xml.Serialization.XmlEnumAttribute("030")]
        Item030,

        /// <comentarios/>
        [Description("Vales de gasolina")]
        [System.Xml.Serialization.XmlEnumAttribute("031")]
        Item031,

        /// <comentarios/>
        [Description("Vales de ropa")]
        [System.Xml.Serialization.XmlEnumAttribute("032")]
        Item032,

        /// <comentarios/>
        [Description("Ayuda para renta")]
        [System.Xml.Serialization.XmlEnumAttribute("033")]
        Item033,

        /// <comentarios/>
        [Description("Ayuda para artículos escolares")]
        [System.Xml.Serialization.XmlEnumAttribute("034")]
        Item034,

        /// <comentarios/>
        [Description("Ayuda para anteojos")]
        [System.Xml.Serialization.XmlEnumAttribute("035")]
        Item035,

        /// <comentarios/>
        [Description("Ayuda para transporte")]
        [System.Xml.Serialization.XmlEnumAttribute("036")]
        Item036,

        /// <comentarios/>
        [Description("Ayuda para gastos de funeral")]
        [System.Xml.Serialization.XmlEnumAttribute("037")]
        Item037,

        /// <comentarios/>
        [Description("Otros ingresos por salarios")]
        [System.Xml.Serialization.XmlEnumAttribute("038")]
        Item038,

        /// <comentarios/>
        [Description("Jubilaciones, pensiones o haberes de retiro")]
        [System.Xml.Serialization.XmlEnumAttribute("039")]
        Item039,

        /// <comentarios/>
        [Description("Jubilaciones, pensiones o haberes de retiro en parcialidades")]
        [System.Xml.Serialization.XmlEnumAttribute("044")]
        Item044,

        /// <comentarios/>
        [Description("Ingresos en acciones o títulos valor que representan bienes")]
        [System.Xml.Serialization.XmlEnumAttribute("045")]
        Item045,

        /// <comentarios/>
        [Description("Ingresos asimilados a salarios")]
        [System.Xml.Serialization.XmlEnumAttribute("046")]
        Item046,

        /// <comentarios/>
        [Description("Alimentación")]
        [System.Xml.Serialization.XmlEnumAttribute("047")]
        Item047,

        /// <comentarios/>
        [Description("Habitación")]
        [System.Xml.Serialization.XmlEnumAttribute("048")]
        Item048,

        /// <comentarios/>
        [Description("Premios por asistencia")]
        [System.Xml.Serialization.XmlEnumAttribute("049")]
        Item049,

        /// <comentarios/>
        [Description("Viaticos")]
        [System.Xml.Serialization.XmlEnumAttribute("050")]
        Item050,
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.sat.gob.mx/sitio_internet/cfd/catalogos/Nomina")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.sat.gob.mx/sitio_internet/cfd/catalogos/Nomina", IsNullable = false)]
    public enum c_TipoRegimen
    {
        /// <comentarios/>
        [Description("Sueldos")]
        [System.Xml.Serialization.XmlEnumAttribute("02")]
        Item02,

        /// <comentarios/>
        [Description("Jubilados")]
        [System.Xml.Serialization.XmlEnumAttribute("03")]
        Item03,

        /// <comentarios/>
        [Description("Pensionados")]
        [System.Xml.Serialization.XmlEnumAttribute("04")]
        Item04,

        /// <comentarios/>
        [Description("Asimilados Miembros Sociedades Cooperativas Produccion")]
        [System.Xml.Serialization.XmlEnumAttribute("05")]
        Item05,

        /// <comentarios/>
        [Description("Asimilados Integrantes Sociedades Asociaciones Civiles")]
        [System.Xml.Serialization.XmlEnumAttribute("06")]
        Item06,

        /// <comentarios/>
        [Description("Asimilados Miembros consejos")]
        [System.Xml.Serialization.XmlEnumAttribute("07")]
        Item07,

        /// <comentarios/>
        [Description("Asimilados comisionistas")]
        [System.Xml.Serialization.XmlEnumAttribute("08")]
        Item08,

        /// <comentarios/>
        [Description("Asimilados Honorarios")]
        [System.Xml.Serialization.XmlEnumAttribute("09")]
        Item09,

        /// <comentarios/>
        [Description("Asimilados acciones")]
        [System.Xml.Serialization.XmlEnumAttribute("10")]
        Item10,

        /// <comentarios/>
        [Description("Asimilados otros")]
        [System.Xml.Serialization.XmlEnumAttribute("11")]
        Item11,

        /// <comentarios/>
        [Description("Otro Regimen")]
        [System.Xml.Serialization.XmlEnumAttribute("99")]
        Item99,
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.sat.gob.mx/sitio_internet/cfd/catalogos/Nomina")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.sat.gob.mx/sitio_internet/cfd/catalogos/Nomina", IsNullable = false)]
    public enum c_RiesgoPuesto
    {

        /// <comentarios/>
        [Description("Clase I")]
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,

        /// <comentarios/>
        [Description("Clase II")]
        [System.Xml.Serialization.XmlEnumAttribute("2")]
        Item2,

        /// <comentarios/>
        [Description("Clase III")]
        [System.Xml.Serialization.XmlEnumAttribute("3")]
        Item3,

        /// <comentarios/>
        [Description("Clase IV")]
        [System.Xml.Serialization.XmlEnumAttribute("4")]
        Item4,

        /// <comentarios/>
        [Description("Clase V")]
        [System.Xml.Serialization.XmlEnumAttribute("5")]
        Item5,
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.sat.gob.mx/sitio_internet/cfd/catalogos/Nomina")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.sat.gob.mx/sitio_internet/cfd/catalogos/Nomina", IsNullable = false)]
    public enum NominaReceptorSindicalizado
    {

        /// <comentarios/>
        [Description("Sí")]
        Sí,

        /// <comentarios/>
        [Description("No")]
        No,
    }
}

