//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DesarrollosPyC.Com.Facturacion.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://pruebasclientes.facturehoy.com:8080/CFDI33/WsEmisionTimbrado33")]
        public string DesarrollosPyC_Com_Facturacion_pruebas_facturehoy_com_WsEmisionTimbrado33 {
            get {
                return ((string)(this["DesarrollosPyC_Com_Facturacion_pruebas_facturehoy_com_WsEmisionTimbrado33"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://pruebas.sefactura.com.mx:3014/sefacturapac/TimbradoService")]
        public string DesarrollosPyC_Com_Facturacion_mx_com_sefactura_pruebas_TimbradoServiceService {
            get {
                return ((string)(this["DesarrollosPyC_Com_Facturacion_mx_com_sefactura_pruebas_TimbradoServiceService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://www.sefactura.com.mx:443/sefacturapac/TimbradoService")]
        public string DesarrollosPyC_Com_Facturacion_mx_com_sefactura_www_TimbradoServiceService {
            get {
                return ((string)(this["DesarrollosPyC_Com_Facturacion_mx_com_sefactura_www_TimbradoServiceService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://wsprod3.facturehoy.com:80/CFDI33/WsEmisionTimbrado33")]
        public string DesarrollosPyC_Com_Facturacion_com_facturehoy_wsprod3_WsEmisionTimbrado33 {
            get {
                return ((string)(this["DesarrollosPyC_Com_Facturacion_com_facturehoy_wsprod3_WsEmisionTimbrado33"]));
            }
        }
    }
}
