//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace DesarrollosPyC.Com.Facturacion.mx.com.sefactura.pruebas {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="TimbradoServicePortBinding", Namespace="http://sefactura.com")]
    public partial class TimbradoServiceService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback cancelacionOperationCompleted;
        
        private System.Threading.SendOrPostCallback timbradoOperationCompleted;
        
        private System.Threading.SendOrPostCallback cancelacionAcuseOperationCompleted;
        
        private System.Threading.SendOrPostCallback cancelacionAcuseXmlOperationCompleted;
        
        private System.Threading.SendOrPostCallback pideConfirmacionOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public TimbradoServiceService() {
            this.Url = global::DesarrollosPyC.Com.Facturacion.Properties.Settings.Default.DesarrollosPyC_Com_Facturacion_mx_com_sefactura_pruebas_TimbradoServiceService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event cancelacionCompletedEventHandler cancelacionCompleted;
        
        /// <remarks/>
        public event timbradoCompletedEventHandler timbradoCompleted;
        
        /// <remarks/>
        public event cancelacionAcuseCompletedEventHandler cancelacionAcuseCompleted;
        
        /// <remarks/>
        public event cancelacionAcuseXmlCompletedEventHandler cancelacionAcuseXmlCompleted;
        
        /// <remarks/>
        public event pideConfirmacionCompletedEventHandler pideConfirmacionCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://sefactura.com", ResponseNamespace="http://sefactura.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string cancelacion([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] solCancelacion solicitud, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string usuario, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string clave) {
            object[] results = this.Invoke("cancelacion", new object[] {
                        solicitud,
                        usuario,
                        clave});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void cancelacionAsync(solCancelacion solicitud, string usuario, string clave) {
            this.cancelacionAsync(solicitud, usuario, clave, null);
        }
        
        /// <remarks/>
        public void cancelacionAsync(solCancelacion solicitud, string usuario, string clave, object userState) {
            if ((this.cancelacionOperationCompleted == null)) {
                this.cancelacionOperationCompleted = new System.Threading.SendOrPostCallback(this.OncancelacionOperationCompleted);
            }
            this.InvokeAsync("cancelacion", new object[] {
                        solicitud,
                        usuario,
                        clave}, this.cancelacionOperationCompleted, userState);
        }
        
        private void OncancelacionOperationCompleted(object arg) {
            if ((this.cancelacionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.cancelacionCompleted(this, new cancelacionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://sefactura.com", ResponseNamespace="http://sefactura.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public resultado timbrado([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string cfdi, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string usuario, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string clave) {
            object[] results = this.Invoke("timbrado", new object[] {
                        cfdi,
                        usuario,
                        clave});
            return ((resultado)(results[0]));
        }
        
        /// <remarks/>
        public void timbradoAsync(string cfdi, string usuario, string clave) {
            this.timbradoAsync(cfdi, usuario, clave, null);
        }
        
        /// <remarks/>
        public void timbradoAsync(string cfdi, string usuario, string clave, object userState) {
            if ((this.timbradoOperationCompleted == null)) {
                this.timbradoOperationCompleted = new System.Threading.SendOrPostCallback(this.OntimbradoOperationCompleted);
            }
            this.InvokeAsync("timbrado", new object[] {
                        cfdi,
                        usuario,
                        clave}, this.timbradoOperationCompleted, userState);
        }
        
        private void OntimbradoOperationCompleted(object arg) {
            if ((this.timbradoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.timbradoCompleted(this, new timbradoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://sefactura.com", ResponseNamespace="http://sefactura.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string cancelacionAcuse([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] solCancelacion solicitud, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string usuario, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string clave) {
            object[] results = this.Invoke("cancelacionAcuse", new object[] {
                        solicitud,
                        usuario,
                        clave});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void cancelacionAcuseAsync(solCancelacion solicitud, string usuario, string clave) {
            this.cancelacionAcuseAsync(solicitud, usuario, clave, null);
        }
        
        /// <remarks/>
        public void cancelacionAcuseAsync(solCancelacion solicitud, string usuario, string clave, object userState) {
            if ((this.cancelacionAcuseOperationCompleted == null)) {
                this.cancelacionAcuseOperationCompleted = new System.Threading.SendOrPostCallback(this.OncancelacionAcuseOperationCompleted);
            }
            this.InvokeAsync("cancelacionAcuse", new object[] {
                        solicitud,
                        usuario,
                        clave}, this.cancelacionAcuseOperationCompleted, userState);
        }
        
        private void OncancelacionAcuseOperationCompleted(object arg) {
            if ((this.cancelacionAcuseCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.cancelacionAcuseCompleted(this, new cancelacionAcuseCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://sefactura.com", ResponseNamespace="http://sefactura.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string cancelacionAcuseXml([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string solicitud, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string usuario, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string clave) {
            object[] results = this.Invoke("cancelacionAcuseXml", new object[] {
                        solicitud,
                        usuario,
                        clave});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void cancelacionAcuseXmlAsync(string solicitud, string usuario, string clave) {
            this.cancelacionAcuseXmlAsync(solicitud, usuario, clave, null);
        }
        
        /// <remarks/>
        public void cancelacionAcuseXmlAsync(string solicitud, string usuario, string clave, object userState) {
            if ((this.cancelacionAcuseXmlOperationCompleted == null)) {
                this.cancelacionAcuseXmlOperationCompleted = new System.Threading.SendOrPostCallback(this.OncancelacionAcuseXmlOperationCompleted);
            }
            this.InvokeAsync("cancelacionAcuseXml", new object[] {
                        solicitud,
                        usuario,
                        clave}, this.cancelacionAcuseXmlOperationCompleted, userState);
        }
        
        private void OncancelacionAcuseXmlOperationCompleted(object arg) {
            if ((this.cancelacionAcuseXmlCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.cancelacionAcuseXmlCompleted(this, new cancelacionAcuseXmlCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://sefactura.com", ResponseNamespace="http://sefactura.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string pideConfirmacion([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string usuario, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string clave, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string rfcEmisor, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string rfcReceptor, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] double monto, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] double tipoCambio) {
            object[] results = this.Invoke("pideConfirmacion", new object[] {
                        usuario,
                        clave,
                        rfcEmisor,
                        rfcReceptor,
                        monto,
                        tipoCambio});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void pideConfirmacionAsync(string usuario, string clave, string rfcEmisor, string rfcReceptor, double monto, double tipoCambio) {
            this.pideConfirmacionAsync(usuario, clave, rfcEmisor, rfcReceptor, monto, tipoCambio, null);
        }
        
        /// <remarks/>
        public void pideConfirmacionAsync(string usuario, string clave, string rfcEmisor, string rfcReceptor, double monto, double tipoCambio, object userState) {
            if ((this.pideConfirmacionOperationCompleted == null)) {
                this.pideConfirmacionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnpideConfirmacionOperationCompleted);
            }
            this.InvokeAsync("pideConfirmacion", new object[] {
                        usuario,
                        clave,
                        rfcEmisor,
                        rfcReceptor,
                        monto,
                        tipoCambio}, this.pideConfirmacionOperationCompleted, userState);
        }
        
        private void OnpideConfirmacionOperationCompleted(object arg) {
            if ((this.pideConfirmacionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.pideConfirmacionCompleted(this, new pideConfirmacionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sefactura.com")]
    public partial class solCancelacion {
        
        private string certificadoField;
        
        private string llavePrivadaField;
        
        private string passwordField;
        
        private string[] uuidField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string certificado {
            get {
                return this.certificadoField;
            }
            set {
                this.certificadoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string llavePrivada {
            get {
                return this.llavePrivadaField;
            }
            set {
                this.llavePrivadaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("uuid", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] uuid {
            get {
                return this.uuidField;
            }
            set {
                this.uuidField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sefactura.com")]
    public partial class resultado {
        
        private string codigoField;
        
        private string statusField;
        
        private string timbreField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string timbre {
            get {
                return this.timbreField;
            }
            set {
                this.timbreField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void cancelacionCompletedEventHandler(object sender, cancelacionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class cancelacionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal cancelacionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void timbradoCompletedEventHandler(object sender, timbradoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class timbradoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal timbradoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public resultado Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((resultado)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void cancelacionAcuseCompletedEventHandler(object sender, cancelacionAcuseCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class cancelacionAcuseCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal cancelacionAcuseCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void cancelacionAcuseXmlCompletedEventHandler(object sender, cancelacionAcuseXmlCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class cancelacionAcuseXmlCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal cancelacionAcuseXmlCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void pideConfirmacionCompletedEventHandler(object sender, pideConfirmacionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class pideConfirmacionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal pideConfirmacionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591